app: voucher-management
service: voucher-management
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    TABLE_NAME: vouchers
    TZ: "Africa/Lagos"

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-dynamodb
  - serverless-offline

functions:
  generateVoucher:
    handler: src/handlers/voucher/generateVoucher.handler
    events:
      - http:
          path: vouchers/generate
          method: post
  retrieveVoucher:
    handler: src/handlers/voucher/retrieveVoucher.handler
    events:
      - http:
          path: vouchers/{code}
          method: get
  invalidateExpiredVouchers:
    handler: src/handlers/voucher/invalidateExpiredVouchers.handler
    events:
      - schedule:
          rate: rate(1 day)
          timezone: Africa/Lagos

resources:
  Resources:
    VouchersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: code
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
