service: voucher-management

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    TABLE_NAME: vouchers
    TZ: "Africa/Lagos"

functions:
  generateVoucher:
    handler: src/handlers/voucher/generateVoucherHandler.handler
    events:
      - http:
          path: vouchers/generate
          method: post
  retrieveVoucher:
    handler: src/handlers/voucher/retrieveVoucherHandler.handler
    events:
      - http:
          path: vouchers/{code}
          method: get
  invalidateExpiredVouchers:
    handler: src/handlers/voucher/invalidateExpiredVouchers.handler
    events:
      - schedule:
          rate: rate(1 day)
          timezone: Africa/Lagos

resources:
  Resources:
    VouchersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: code
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
