app: voucher-management
service: voucher-management
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  architecture: x86_64
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 512
  timeout: 28
  stackName: voucher-management-${opt:stage, 'dev'}
  deploymentMethod: changesets
  environment:
    DYNAMODB_ENDPOINT: ${env:DYNAMODB_ENDPOINT}
    VOUCHER_TABLE: ${env:TABLE_NAME}
    TZ: ${env:TZ}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:*"
          Resource: "*"

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-dynamodb
  - serverless-offline

custom:
  serverless-dynamodb:
    stages:
      - dev
    start:
      docker: true
      port: 8092
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      volume: true
      convertEmptyValues: true
    migration:
      dir: offline/migrations
  esbuild:
    watch:
      pattern: "src/**/*.ts"

functions:
  generateVoucher:
    handler: src/handlers/voucher/generateVoucher.handler
    events:
      - http:
          path: vouchers/generate
          method: post
  retrieveVoucher:
    handler: src/handlers/voucher/retrieveVoucher.handler
    events:
      - http:
          path: vouchers/{code}
          method: get
  invalidateExpiredVouchers:
    handler: src/handlers/voucher/invalidateExpiredVouchers.handler
    events:
      - schedule:
          rate: rate(1 day)
          timezone: Africa/Lagos

resources:
  Resources:
    VouchersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.VOUCHER_TABLE}
        AttributeDefinitions:
          - AttributeName: code
            AttributeType: S
        KeySchema:
          - AttributeName: code
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
